### ISSUE TITLE
question

### ISSUE THREAD

**Issue by imthecheeser** [EvilBytecode/Sryxen#1]
why does it download a .bin file?

**Comment by EvilBytecode** [comment]
So it can get the info, either i can
Store it on server or on github.

**Comment by imthecheeser** [comment]
> So it can get the info, either i can Store it on server or on github.

it closes my browsers and its literally named sryxen built im like 99.9999999% sure its a rat

**Comment by EvilBytecode** [comment]
Of course, it’s the payload—that’s the whole point. If you’re unsure about the binary, I can rework it to store the data on a server, but that would require a rewrite. If you know how to code, you can simply compile the stealer yourself and convert it to a binary using ```pe2shc```. I've already done this and can confirm that it’s not a RAT; it’s a logger. The source code is available for review.

As for closing browsers, that’s necessary to dump the cookies because of Chrome’s App Bound Encryption (ABE) introduced in version 127+.
The stealer just runs to get all the info to store it in ```%temp%\%username%```

**Comment by imthecheeser** [comment]
> Of course, it’s the payload—that’s the whole point. If you’re unsure about the binary, I can rework it to store the data on a server, but that would require a rewrite. If you know how to code, you can simply compile the stealer yourself and convert it to a binary using `pe2shc`. I've already done this and can confirm that it’s not a RAT; it’s a logger. The source code is available for review.
> 
> As for closing browsers, that’s necessary to dump the cookies because of Chrome’s App Bound Encryption (ABE) introduced in version 127+. The stealer just runs to get all the info to store it in `%temp%\%username%`

the "sryxen_loader.ps1" file literally downloads it and runs it why would u put a payload inside of the loader

**Comment by EvilBytecode** [comment]
Because it's efficient, that's why. Embedding the payload directly into the loader simplifies execution and avoids unnecessary steps. The loader’s sole purpose is to execute the payload, so why overcomplicate it with extra downloads or dependencies? If you don’t trust it, decompile and review the source yourself instead of making baseless assumptions.
