### ISSUE TITLE
Remove playit.gg integration, service violates our TOS

### ISSUE THREAD

**Issue by loriopatrick** [EvilBytecode/Sryxen#2]
Hi there,

I'm the owner of playit.gg, using playit.gg's services for this software violates our terms of service: https://playit.gg/terms

Please remove playit.gg from your software.

**Comment by EvilBytecode** [comment]
Hi Lori,

Thank you for reaching out and for providing the link to your Terms of Service. After reviewing the relevant clauses, I would like to address your concerns:

Non-Circumvention and Intended Use: My software does not attempt to circumvent or exceed any limitations set by your platform, nor does it interfere with your APIs, servers, or other users as outlined in Section 3. Prohibited Uses. The software uses your publicly accessible services as intended, without overloading, disrupting, or damaging them.

Lawful Use: As stated in my software's README, it is provided for educational purposes only. The usage of your services via my tool does not promote or facilitate any unlawful activity, nor does it breach compliance with applicable laws (Section 3).

Educational and Open-Source Nature: The project is open-source and shared under a license explicitly disclaiming misuse or harm caused by third-party users. It operates within the bounds of fair use and does not claim to be affiliated with, endorsed by, or misrepresent Playit.gg in any way.

Tunneling and User Content: Section 3.1 of your terms appears to acknowledge that tunneling may occur through your services. As per my understanding, this software does not violate the limitations of the license users agree to when accessing your platform.

If there are specific provisions or technical activities that you believe this project infringes upon, I kindly ask you to provide more detailed clarification or evidence. I am happy to review and address any substantiated concerns.

I appreciate the time you’ve taken to reach out and would like to ensure that this project remains compliant with all relevant terms.

**Comment by EvilBytecode** [comment]
Dear Lori,

Your claim that my use of Playit.gg violates your Terms of Service is completely unsubstantiated, and I reject your demand to remove references to your platform. After reviewing your TOS, it is clear that my software does not breach any specific clause. It lawfully utilizes publicly available services as intended, without damaging, disabling, or impairing your platform. Your failure to identify any specific violation renders your claim baseless.

Your unwarranted demand constitutes tortious interference with my legitimate activities and, if continued, may compel me to take legal action to protect my rights. Additionally, your accusations, lacking any evidence, border on defamation, as they imply wrongful conduct on my part. Such statements harm my reputation and expose you to potential legal liability.

I demand that you immediately cease and desist from making baseless claims. If you fail to provide a detailed explanation of how my project violates your TOS within seven (7) days, I will consider further demands as harassment and interference, and I will take appropriate legal action, including seeking damages for any harm caused.

I trust we can resolve this amicably, but I will not hesitate to act swiftly to protect my rights if this behavior persists.

Sincerely,
Evilbytecode

**Comment by loriopatrick** [comment]
Request has been satisfied.

**Comment by LunerLA2** [comment]
This is a very cool issue. I hope someone doesnt download a older version, make a repo and not give a fuck 😓 

https://github.com/LunerLA2/Sryxen-Playit.gg-Version
